# Generated by Django 3.1.4 on 2020-12-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('details_title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'тип блюда',
                'verbose_name_plural': 'типы блюд',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('receipt', models.TextField()),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PovareshkaProject.coursetype')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
            },
        ),
    ]
