# Generated by Django 3.1.4 on 2020-12-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PovareshkaProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='type_name',
            field=models.CharField(default='soop', max_length=10),
            preserve_default=False,
        ),
    ]
