# Generated by Django 3.1.4 on 2020-12-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PovareshkaProject', '0003_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='receipt',
            field=models.TextField(blank=True),
        ),
    ]
